#!/usr/bin/env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook

---
- hosts: localhost
  connection: local
  vars:
    keywords:
      - 'test'
      - 'ansible'
    safe: 'MY_SAFE'
  tasks:
    - debug:
        msg: "{{lookup('cyberarkpasswordvault', 'test', safe=safe, passprops=True, validate_certs=False)}}"

    - debug:
        var: item
      loop: "{{query('cyberarkpasswordvault', 'ansible', 'test', safe=safe, validate_certs=False)}}"

    - debug:
        var: item
      loop: "{{query('cyberarkpasswordvault', keywords=keywords, safe=safe, validate_certs=False)}}"