
- fail: 
    msg: "Bailing out. Requires a reason for creating password vault requests: 'pwv_reason'"
  when: pwv_reason is not defined
  delegate_to: localhost
- fail: 
    msg: "Bailing out. Requires a time period (in seconds) for how long the requests should be valid: 'pwv_request_period'"
  when: pwv_request_period is not defined
  delegate_to: localhost
- fail: 
    msg: "Bailing out. Requires 'cyberark_url'. Can be set using the CYBERARK_URL environment variable"
  when: cyberark_url is not defined
  delegate_to: localhost
- fail: 
    msg: "Bailing out. Requires 'cyberark_username'. Can be set using the CYBERARK_USERNAME environment variable"
  when: cyberark_username is not defined
  delegate_to: localhost
- fail: 
    msg: "Bailing out. Requires 'cyberark_password'. Can be set using the CYBERARK_PASSWORD environment variable"
  when: cyberark_password is not defined
  delegate_to: localhost

- uri:
    url: "{{cyberark_url}}/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon"
    method: POST
    return_content: yes
    body: "{{ lookup('template', 'logon_body.json') }}"
    body_format: json
  register: pwv_login_token
  delegate_to: localhost

- include_tasks: 'tasks/request_pwv_single.yml'
  vars: 
    cyberark_login_token: "{{pwv_login_token['json']['CyberArkLogonResult']}}"
  loop_control:
    loop_var: host_item
  delegate_to: localhost
  loop: "{{ansible_play_hosts}}"

